version: '3.8'

services:
  ur5_ros2_interface:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: ur5_ros2_interface
    container_name: ur5_ros2_interface_container
    stdin_open: true
    tty: true
    network_mode: "host"
    ipc: host

    privileged: true

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority:rw
      - /dev:/dev
      - ./config:/home/ros2_ws/config
      - ./src:/home/ros2_ws/src
